name: Lint tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/lint/golint@latest

      - name: Run lint test
        run: |
          go vet ./...
          staticcheck ./...
          golint -set_exit_status=1 ./...
